# Software
https://manual.gromacs.org/current/download.html
https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/
https://avogadro.cc/install/index.html



# The 2022 version is different; you need to add the -ter parameter and select 'Start terminus MET-1: NH3+' and 'End terminus LYS-371: COO-'. (https://gromacs.bioexcel.eu/t/atom-c1-not-found-in-building-block-pdb2gmx-fatal-error/5206)
gmx_mpi pdb2gmx -f receptor.pdb -o rec_processed.gro -ter


cd ligand1  # Go to the ligand-specific folder (e.g., ligand1) to run and store MD output files for the protein and ligand1.
cp -R ../charmm36-jul2022.ff/ .
# The pro_lig.pdb file was generated by importing the original protein PDB and the docked ligand SDF (converted from Vina's output PDBQT to SDF using Meeko) into PyMOL, and then saving it as this file.
grep UNL pro_lig.pdb >lig.pdb
# grep HETATM pro_lig.pdb >lig.pdb  # Extract the ligand information. Modify the grep 'HETATM' pattern to match your specific ligand file's content
# Avogadro:  Add hydrogens to lig.pdb and save it as mol2.
# Modify the small molecule (lig.mol2): change .... to lig, and change UNK* to lig.

perl ../script/sort_mol2_bonds.pl lig.mol2 lig_fix.mol2
# Go to CGenFF (https://cgenff.com/) to generate the .str file.

## Note: Keep the version in the warning consistent with your own version.
source activate gromacs
python ../script/cgenff_charmm2gmx_py3_nx2.py lig lig_fix.mol2 lig_fix.str ../charmm36-jul2022.ff
conda deactivate


gmx_mpi editconf -f lig_ini.pdb -o lig.gro
# Before MD: modify .gro/.top files (e.g., add ligand info, system restraints). Using a script is easier.
# Backup the original file first, so you can restore it if errors occur.
#mkdir ori
#cp rec_processed.gro ori/
#cp posre.itp ori/
#topol.top ori/

# Modify complex.gro:
perl ../script/addatom.pl lig.gro rec_processed.gro


#cp ../topol.top .
# Modify the topol file (already modified) [Note: Add the ligand information]


# Box and water model
gmx_mpi editconf -f complex.gro -o newbox.gro -bt dodecahedron -d 1.0
gmx_mpi solvate -cp newbox.gro -cs spc216.gro -p topol.top -o solv.gro


## Energy minimization configuration (requires ion.mdp)
gmx_mpi grompp -f ../mdp/ions.mdp -c solv.gro -p topol.top -o ions.tpr
## add NACL
gmx_mpi genion -s ions.tpr -o solv_ions.gro -p topol.top -pname SOD -nname CLA -neutral  #2022版charmm的ions.itp：NA为SOD  CL为CLA
### Select 15 (SOL) to replace NaCl

## Energy minimization (requires em.mdp)
gmx_mpi grompp -f ../mdp/em.mdp -c solv_ions.gro -p topol.top -o em.tpr
gmx_mpi mdrun -v -deffnm em

##1. Apply constraints to the ligand 2. Handling of temperature coupling groups
### Generate a ligand position restraint topology
#### First, create an index group for the ligand that contains only non-hydrogen atoms
gmx_mpi make_ndx -f lig.gro -o index_lig.ndx
 > 0 & ! a H*
 > q
### Use genrestr to select the above non-hydrogen ligand group
gmx_mpi genrestr -f lig.gro -n index_lig.ndx -o posre_lig.itp -fc 1000 1000 1000
#### select 3

### Add the restraint information to topol.top.
#### Add different restraint conditions for different restraints:
perl ../script/addmode2.pl topol.top

##如果对每个分子类型进行温度耦合（即tc-grps = Protein lig SOL CL），会造成崩溃（耦合算法的不稳定性，如配体和CL）
##可以设置为tc-grps = Protein Non-Protein，但是蛋白和配体互作性高，可以看成整体
###合并蛋白和配体
gmx_mpi make_ndx -f em.gro -o index.ndx
> 1 | 13
> 15 | 14   #根据自己的参数来
> q
##现在可以将tc-grps = Protein_lig Water_and_ions看做为Protein Non-Protein
###执行NVT（需要nvt.mdp）
gmx_mpi grompp -f ../mdp/nvt.mdp -c em.gro -r em.gro -p topol.top -n index.ndx -o nvt.tpr
gmx_mpi mdrun -v -deffnm nvt
###执行NPT（需要npt.mdp）
gmx_mpi grompp -f ../mdp/npt.mdp -c nvt.gro -t nvt.cpt -r nvt.gro -p topol.top -n index.ndx -o npt.tpr
gmx_mpi mdrun -v -deffnm npt


gmx_mpi grompp -f ../mdp/md.mdp -c npt.gro -t npt.cpt -p topol.top -n index.ndx -o md_0_10.tpr
gmx_mpi mdrun -v -deffnm md_0_10  # 100ns 根据mdp文件修改
#gmx_mpi mdrun -v -deffnm md_0_10  -gpu_id 1



#rmsd
###Choose "Protein" for centering and "System" for output. 
echo 1 0 | gmx_mpi trjconv -s md_0_10.tpr -f md_0_10.xtc -o md_0_10_center.xtc -center -pbc mol -ur compact
gmx_mpi make_ndx -f em.gro -n index.ndx <<EOF
13 & ! a H*
name 20 lig_Heavy
q
EOF
###选择backbone和20
echo 4 20 | gmx_mpi rms -s em.tpr -f md_0_10_center.xtc -n index.ndx -tu ns -o rmsd_lig.xvg


#gmx_MMPBSA
#gmx_MMPBSA -O -i mmpbsa_charm.in -cs md_0_10.tpr -ci index.ndx -cg 1 13 -ct md_0_10_center.xtc
source activate gmxMMPBSA

#修改平衡的frame，比如75-100在mmpbsa_charm.in里面改,更多参数修改，请参考gmxMMPBSA手册：https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/
cd mmpbsa
mpirun -np 10 gmx_MMPBSA MPI -O -i mmpbsa_charm.in -cs ../md_0_10.tpr -ci ../index.ndx -cg 1 13 -ct ../md_0_10_center.xtc -cp ../topol.top



